import type { CitizenFormField } from '@/types';
import { races } from './races';
import { genders } from './genders';

export default (hiddenFields: string[]): CitizenFormField[] => {
	const fields: CitizenFormField[] = [
		{
			name: 'name',
			label: 'Nome',
			required: true,
			rules: 'required|min:5',
			colSpan: 6,
			placeholder: 'Nome do usuário',
			component: 'CdsTextInput',
		},
		{
			name: 'cns',
			label: 'CNS',
			required: true,
			rules: 'required|cns',
			colSpan: 3,
			placeholder: '000 0000 0000 0000',
			mask: '### #### #### ####',
			component: 'CdsTextInput',
		},
		{
			name: 'cpf',
			label: 'CPF',
			required: true,
			rules: 'required|cpf',
			colSpan: 3,
			placeholder: '000.000.000-00',
			mask: '###.###.###-##',
			component: 'CdsTextInput',
		},
		{
			name: 'birth_date',
			label: 'Data de nascimento',
			required: true,
			rules: 'required',
			colSpan: 3,
			component: 'CdsDateInput',
			maxDate: new Date().toISOString().split('T')[0],
		},
		{
			name: 'identification_document',
			label: 'RG',
			required: false,
			rules: '',
			colSpan: 3,
			component: 'CdsTextInput',
			mask: '###########',
		},
		{
			name: 'race',
			label: 'Raça/Cor',
			required: true,
			rules: 'required',
			colSpan: 2,
			component: 'CdsSelect',
			options: races,
			optionsField: 'name',
		},
		{
			name: 'gender',
			label: 'Sexo',
			required: true,
			rules: 'required',
			colSpan: hiddenFields.includes('race') ? 3 : 2,
			component: 'CdsSelect',
			options: genders(),
			optionsField: 'name',
		},
		{
			name: 'pregnant',
			label: 'Está gestante',
			required: false,
			rules: '',
			colSpan: 2,
			component: 'CdsCheckbox',
		},
		{
			name: 'phone',
			label: 'Telefone',
			required: false,
			rules: '',
			colSpan: 3,
			component: 'CdsTextInput',
			mask: '(##) #####-####',
			placeholder: '(00) 00000-0000',
		},
		{
			name: 'email',
			label: 'E-mail',
			required: false,
			rules: '',
			colSpan: 3,
			component: 'CdsTextInput',
			placeholder: 'seu.email@exemplo.com',
		},
		{
			name: 'street',
			label: 'Rua',
			required: true,
			rules: 'required',
			colSpan: 4,
			component: 'CdsTextInput',
			placeholder: 'Ex.: Rua Coronel Exemplio Lima',
		},
		{
			name: 'number',
			label: 'Número',
			required: true,
			rules: 'required',
			colSpan: 2,
			component: 'CdsTextInput',
			placeholder: '00',
		},
		{
			name: 'complement',
			label: 'Complemento',
			required: false,
			rules: '',
			colSpan: 3,
			component: 'CdsTextInput',
			placeholder: 'Ex.: Casa, prédio...',
		},
		{
			name: 'neighborhood',
			label: 'Bairro',
			required: true,
			rules: 'required',
			colSpan: 3,
			component: 'CdsTextInput',
			placeholder: 'Ex.: Centro',
		},
	];

	return fields.filter(field => !hiddenFields.includes(field.name));
};
